### ISSUE TITLE
mintupgrade: AttributeError: module 'inspect' has no attribute 'getargspec'

### ISSUE THREAD

**Issue by siteleas** [linuxmint/mintupgrade#78]
When I perform:

`sudo mintupgrade`

I receive the following error:

```
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintupgrade/mintupgrade.py", line 21, in <module>
    from checks import *
  File "/usr/lib/linuxmint/mintupgrade/checks.py", line 21, in <module>
    import mintcommon.aptdaemon
  File "/usr/lib/python3/dist-packages/mintcommon/aptdaemon.py", line 9, in <module>
    import aptdaemon.client
  File "/usr/lib/python3/dist-packages/aptdaemon/client.py", line 54, in <module>
    class AptTransaction(GObject.Object):
  File "/usr/lib/python3/dist-packages/aptdaemon/client.py", line 656, in AptTransaction
    @convert_dbus_exception
     ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/aptdaemon/errors.py", line 177, in convert_dbus_exception
    argnames, varargs, kwargs, defaults = inspect.getargspec(func)
                                          ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?

```

How do I solve this issue?

```
 ~ > lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	LMDE 4 (debbie)
Release:	4
Codename:	debbie
```

**Comment by Jeremy7701** [comment]
By installing LMDE6 - you won't have received any support for a number of years!

**Comment by clefebvre** [comment]
Sorry @siteleas, LMDE 4 has been EOL for a while now indeed.
