### ISSUE TITLE
Upgrade vom 20.3 to 21.3 fails

### ISSUE THREAD

**Issue by MartinPabela** [linuxmint/mintupgrade#80]
After passing all steps before ...
Running check 'Phase 3: Aktualisierung'
=================
APT Repositories:
=================
Repos:     No active apt repos in: /etc/apt/sources.list 
           No active apt repos in: /etc/apt/sources.list.d/home:alex_sh:gsmartcontrol:stable_latest.list 
           No active apt repos in: /etc/apt/sources.list.d/jtaylor-keepass-focal.list 
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http://linux-mint.froonix.org vanessa main upstream import backport
           2: deb http://mirror.23media.com/ubuntu jammy main restricted universe multiverse
           3: deb http://mirror.23media.com/ubuntu jammy-updates main restricted universe multiverse
           4: deb http://mirror.23media.com/ubuntu jammy-backports main restricted universe multiverse
           5: deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
           No active apt repos in: /etc/apt/sources.list.d/syncthing.list 
=================

... the upgrade dies in ...

Running check 'Sitzungssperrung'

in the GUI I see:
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintupgrade/checks.py", line 94, in run
    self.do_run()
  File "/usr/lib/linuxmint/mintupgrade/checks.py", line 832, in do_run
    subprocess.Popen(cmd)
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1639, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not NoneType

My terminal is a terminal of root, the X runs as a user, which has allowed root to start some X session using xhost command

**Comment by MartinPabela** [comment]
Additional info: mintupgrade is version 2024.01.12

**Comment by terr72** [comment]
> My terminal is a terminal of root, the X runs as a user, which has allowed root to start some X session using xhost command

That's the culprit. You should run a `sudo mintupgrade` as user, not root.
This should IMHO however be caught earlier in the process by mintupgrade - or at least be shown in a way that's easier to understand.
